### ISSUE TITLE
Export as SVG or other format readable from different mipui installation

### ISSUE THREAD

**Issue by turion** [amishne/mipui#156]
I'm really happy this exists! The only thing that prevents me from using it is an export function that exports the data in such a way that I could reimport it into my local mipui installation. This way, I could develop maps, save them on my computer and edit them when mipui.net goes offline. (Because, let's be honest, "Every Mipui map [...] will remain [online] forever." is a promise noone can be expected to fulfil.)

**Comment by amishne** [comment]
> (Because, let's be honest, "Every Mipui map [...] will remain [online] forever." is a promise noone can be expected to fulfil.)
Fair enough, and this is one of the reasons I made this open-source - so that the tool is still functional if it ever goes offline.

In any case, I will enable a local save and load options once I'm more confident that the map storage format is stable; right now there are still a few changes coming down the line that might cause backward incompatibility. So I'm closing this ticket for now.

However, the functionality is actually already there - you can save and load a map from the debug menu, which is available if you're running locally, and you can enable it on mipui.net/app by typing "state.menu.addDebugMenu()" in the dev tools console. Just be advised that I currently do **not** guarantee backward compatibility for locally saved files, so don't expect it to work flawlessly in future versions!
